# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stable_matching_string <- function(proposer_matrix, proposer_syms, acceptor_matrix, acceptor_syms) {
    .Call(`_praxi_stable_matching_string`, proposer_matrix, proposer_syms, acceptor_matrix, acceptor_syms)
}

stable_matching_int <- function(proposer_matrix, proposer_syms, acceptor_matrix, acceptor_syms) {
    .Call(`_praxi_stable_matching_int`, proposer_matrix, proposer_syms, acceptor_matrix, acceptor_syms)
}

